qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Sven Fillinger
email: sven.fillinger@qbic.uni-tuebingen.de
project_name: qoffer-2-portlet
project_short_description: qOffer assists in managing and creating offers
version: 1.1.2
domain: portlet
language: groovy
project_slug: qoffer-2-portlet
project_slug_no_hyphen: qoffer_2_portlet
template_version: '1.1.0-SNAPSHOT # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: qbicsoftware
creator_github_username: sven1103
is_github_repo: false
is_repo_private: false
is_github_orga: false
github_orga: qbicsoftware
copyright_holder: QBiC
license: MIT
main_class_prefix: qOffer
use_openbis_client: yes
use_openbis_raw_api: yes
use_qbic_databases: yes
use_vaadin_charts: yes
